- name: 'Install initial configuration'
  hosts: 'gitea-vm'
  become: true
  vars:
    ansible_user: 'server-admin'

  tasks:
    - name: 'Install packages'
      ansible.builtin.apt:
        name:
          - 'podman'
          - 'slirp4netns'
        state: 'present'
        update_cache: 'yes'

    - name: 'Create user for podman management'
      ansible.builtin.user:
        name: 'podman-admin'
        comment: 'User for podman management'
        shell: '/bin/bash'

    - name: 'Set authorized key for user podman-admin'
      ansible.posix.authorized_key:
        user: 'podman-admin'
        state: 'present'
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/personal_id_ed25519.pub') }}"

    - name: 'Check if podman-admin is lingering'
      stat:
        path: '/var/lib/systemd/linger/podman-admin'
      register: 'user_lingering'

    - name: 'Enable lingering is needed'
      command: "loginctl enable-linger podman-admin"
      when:
        - 'not user_lingering.stat.exists'
