- name: Config storage pools
  hosts: hypervisor
  vars:
    ansible_user: virtualization-admin

  tasks:
    - name: Ensure storage pool path exist
      file:
        mode: u=rwx,g=rx,o=rx
        path: '/home/virtualization-admin/libvirt/images/pool'
        state: directory

    - name: Ensure that a pool is present
      community.libvirt.virt_pool:
        state: present
        name: filesystem_pool
        xml: '{{ lookup("file", "filesystem_pool.xml") }}'

    - name: Ensure that a pool is active
      community.libvirt.virt_pool:
        state: active
        name: filesystem_pool

    - name: Ensure that a given pool will be started at boot
      community.libvirt.virt_pool:
        autostart: true
        name: filesystem_pool
