- name: Config virtual networks
  hosts: hypervisor
  vars:
    ansible_user: virtualization-admin

  tasks:
    - name: Ensure that a network is present
      community.libvirt.virt_net:
        state: present
        name: nat_network
        xml: '{{ lookup("file", "nat_network.xml") }}'

    - name: Ensure that a network is active
      community.libvirt.virt_net:
        state: active
        name: nat_network

    - name: Ensure that a given network will be started at boot
      community.libvirt.virt_net:
        autostart: true
        name: nat_network
