- name: Deploy VM
  hosts: hypervisor
  vars:
    ansible_user: virtualization-admin

  tasks:
    # set default network autostart

    - name: Copy base image to libvirt directory
      ansible.builtin.copy:
        src: '/home/virtualization-admin/libvirt/images/templates/debian-12-nocloud-amd64.qcow2'
        dest: '/home/virtualization-admin/libvirt/images/test_vm.qcow2'
        force: no
        remote_src: yes
        mode: 0660
      register: copy_results
    - debug:
        var: copy_results
