- name: Install initial configuration
  hosts: hypervisor
  vars:
    ansible_user: root

  tasks:
    - name: Create admin
      ansible.builtin.user:
        name: admin
        comment: User for system administration
        shell: /bin/bash

    - name: Create user for virtualization management
      ansible.builtin.user:
        name: virtualization-admin
        comment: User for virtualization management
        groups:
          - libvirt
          - kvm
        shell: /bin/bash

    - name: Set authorized key for admin
      ansible.posix.authorized_key:
        user: admin
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/personal_id_ed25519.pub') }}"

    - name: Set authorized key for user virtualization-admin
      ansible.posix.authorized_key:
        user: virtualization-admin
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/personal_id_ed25519.pub') }}"

    - name: Restart sshd
      ansible.builtin.systemd_service:
        name: ssh.service
        state: restarted

    - name: Install tools packages
      ansible.builtin.apt:
        name:
          - curl
          - python3-lxml
        state: present

    - name: Copy sshd_config
      ansible.builtin.copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
      tags: init

    - name: Install virtualization packages
      ansible.builtin.apt:
        name:
          - qemu-system-x86
          - libvirt-daemon-system
        state: present

    - name: Restart libvirtd
      ansible.builtin.systemd_service:
        name: libvirtd.service
        state: restarted
