- name: Upgrade
  hosts: hypervisor
  become: true
  vars:
    ansible_user: admin

  tasks:
    - name: Upgrade all apt packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        autoremove: true
        clean: true
      register: apt

    - debug:
        var: apt
