- name: 'Install VM'
  hosts: 'hypervisor'
  vars:
    ansible_user: 'virtualization-admin'
  vars_files:
    - 'vars/default.yaml'

  tasks:
    - name: 'Ensure that storage pool path exist'
      file:
        mode: 'u=rwx,g=rx,o=rx'
        path: '{{ vm_pool_dir }}'
        state: 'directory'

    - name: 'Ensure that pool is present'
      community.libvirt.virt_pool:
        state: 'present'
        name: '{{ vm_pool_name }}'
        xml: '{{ lookup("template", "vm-pool.xml") }}'

    - name: 'Ensure that pool will be started at boot'
      community.libvirt.virt_pool:
        autostart: true
        name: '{{ vm_pool_name }}'

    - name: 'Create VM disk image'
      ansible.builtin.shell: '/usr/bin/qemu-img create -b {{ base_image_path }} -f qcow2 -F qcow2 {{ vm_disk_image_path }} 8G'

    - name: 'Create cloud-init user-data'
      template:
        src: 'user-data.yaml.j2'
        dest: '{{ cloud_init_user_data_path }}'

    - name: 'Create cloud-init meta-data'
      template:
        src: 'meta-data.yaml.j2'
        dest: '{{ cloud_init_meta_data_path }}'

    - name: 'Create cloud-init network-config'
      template:
        src: 'network-config.yaml.j2'
        dest: '{{ cloud_init_network_config_path }}'

    - name: 'Create cloud-init configuration image'
      command: 'genisoimage -output {{ cloud_init_image_path }} -V cidata -r -J {{ cloud_init_user_data_path }} {{ cloud_init_meta_data_path }} {{ cloud_init_network_config_path }}'
