- name: 'Install VM'
  hosts: 'hypervisor'
  vars:
    ansible_user: 'virtualization-admin'
    vm_pool_dir: '/home/virtualization-admin/libvirt/pools/gitea-vm'
    vm_disk_image_path: '/home/virtualization-admin/libvirt/pools/gitea-vm/gitea-vm.qcow2'
    base_image_path: '/home/virtualization-admin/libvirt/images/debian-12-generic-amd64.qcow2'

  tasks:
    - name: 'Ensure that storage pool path exist'
      file:
        mode: 'u=rwx,g=rx,o=rx'
        path: '{{ vm_pool_dir }}'
        state: 'directory'

    - name: 'Ensure that pool is present'
      community.libvirt.virt_pool:
        state: 'present'
        name: 'gitea-vm-pool'
        xml: '{{ lookup("ansible.builtin.template", "gitea-vm-pool.xml") }}'

    - name: 'Ensure that pool will be started at boot'
      community.libvirt.virt_pool:
        autostart: true
        name: 'gitea-vm-pool'

    - name: 'Create VM disk image'
      ansible.builtin.shell: '/usr/bin/qemu-img create -b {{ base_image_path }} -f qcow2 -F qcow2 {{ vm_disk_image_path }} 8G'

    - name: 'Create cloud-init user-data'
      template:
        src: 'user-data.j2'
        dest: '{{ vm_pool_dir }}/user-data'

    - name: 'Create cloud-init meta-data'
      template:
        src: 'meta-data.j2'
        dest: '{{ vm_pool_dir }}/meta-data'

    - name: 'Create cloud-init network-config'
      template:
        src: 'network-config.j2'
        dest: '{{ vm_pool_dir }}/network-config'

    - name: 'Create cloud-init configuration image'
      command: 'genisoimage -output {{ vm_pool_dir }}/cidata.iso -V cidata -r -J {{ vm_pool_dir }}/user-data {{ vm_pool_dir }}/meta-data {{ vm_pool_dir }}/network-config'
