- name: 'Start VM'
  hosts: 'hypervisor'
  vars:
    ansible_user: 'virtualization-admin'
  vars_files:
    - 'vars/default.yaml'

  tasks:
    - name: 'Define VM'
      community.libvirt.virt:
        command: 'define'
        xml: '{{ lookup("template", "vm.xml.j2") }}'
        autostart: true

    - name: 'Ensure that pool is active'
      community.libvirt.virt_pool:
        state: 'active'
        name: '{{ vm_pool_name }}'

    - name: 'Ensure that VM is running'
      community.libvirt.virt:
        state: 'running'
        name: '{{ vm_name }}'
