- name: 'Stop VM'
  hosts: 'hypervisor'
  vars:
    ansible_user: 'virtualization-admin'

  tasks:
    - name: 'Ensure that VM is shutdown'
      community.libvirt.virt:
        state: 'shutdown'
        name: 'gitea-vm'

    - name: 'Ensure that pool is inactive'
      community.libvirt.virt_pool:
        state: 'inactive'
        name: 'gitea-vm-pool'
