- name: 'Uninstall VM'
  hosts: 'hypervisor'
  vars:
    ansible_user: 'virtualization-admin'
  vars_files:
    - 'vars/default.yaml'

  tasks:
    - name: 'Check that VM exists'
      shell: "virsh --connect qemu:///system domstate {{ vm_name }} >/dev/null 2>&1 && echo 'yes' || echo 'no'"
      register: 'vm_exists'
      changed_when: false

    - name: 'Destroy VM'
      when: "vm_exists.stdout == 'yes'"
      community.libvirt.virt:
        state: 'destroyed'
        name: '{{ vm_name }}'

    - name: 'Undefine VM'
      when: "vm_exists.stdout == 'yes'"
      community.libvirt.virt:
        command: 'undefine'
        name: '{{ vm_name }}'

    - name: 'Undefine pool'
      community.libvirt.virt_pool:
        state: 'absent'
        name: '{{ vm_pool_name }}'

    - name: 'Remove VM disk image'
      ansible.builtin.file:
        path: '{{ vm_disk_image_path }}'
        state: 'absent'

    - name: 'Remove cloud-init disk image'
      ansible.builtin.file:
        path: '{{ cloud_init_image_path }}'
        state: 'absent'

    - name: 'Remove cloud-init user-data'
      ansible.builtin.file:
        path: '{{ cloud_init_user_data_path }}'
        state: 'absent'

    - name: 'Remove cloud-init meta-data'
      ansible.builtin.file:
        path: '{{ cloud_init_meta_data_path }}'
        state: 'absent'

    - name: 'Remove cloud-init network-config'
      ansible.builtin.file:
        path: '{{ cloud_init_network_config_path }}'
        state: 'absent'
