- name: Install VM
  hosts: hypervisor
  vars:
    ansible_user: virtualization-admin

  tasks:
    - name: Ensure that network is present
      community.libvirt.virt_net:
        state: present
        name: test_vm_network
        xml: '{{ lookup("file", "test_vm_network.xml") }}'

    - name: Ensure that network will be started at boot
      community.libvirt.virt_net:
        autostart: true
        name: test_vm_network

    - name: Ensure that storage pool path exist
      file:
        mode: u=rwx,g=rx,o=rx
        path: '/home/virtualization-admin/libvirt/pools/test_vm'
        state: directory

    - name: Ensure that pool is present
      community.libvirt.virt_pool:
        state: present
        name: test_vm_pool
        xml: '{{ lookup("file", "test_vm_pool.xml") }}'

    - name: Ensure that pool will be started at boot
      community.libvirt.virt_pool:
        autostart: true
        name: test_vm_pool

    - name: Create VM disk image
      ansible.builtin.shell: '/usr/bin/qemu-img create -f qcow2 -o preallocation=metadata /home/virtualization-admin/libvirt/pools/test_vm/test_vm.qcow2 8G'
      register: resize_result
    - debug:
        var: resize_result

    - name: Copy base image contents and resize VM disk image
      ansible.builtin.shell: '/usr/bin/virt-resize --expand /dev/sda1 /home/virtualization-admin/libvirt/images/debian-12-nocloud-amd64.qcow2 /home/virtualization-admin/libvirt/pools/test_vm/test_vm.qcow2'
      register: resize_result
    - debug:
        var: resize_result

    - name: Fix grub config after resize
      ansible.builtin.shell: "/usr/bin/virt-customize -a /home/virtualization-admin/libvirt/pools/test_vm/test_vm.qcow2 --run-command 'grub-install /dev/sda'"
      register: resize_result
    - debug:
        var: resize_result

    - name: Generate SSH keys
      ansible.builtin.shell: "/usr/bin/virt-customize -a /home/virtualization-admin/libvirt/pools/test_vm/test_vm.qcow2 --run-command 'ssh-keygen -A'"
      register: resize_result
    - debug:
        var: resize_result

    - name: Define VM
      community.libvirt.virt:
        command: define
        xml: '{{ lookup("file", "test_vm.xml") }}'
        autostart: true
