- name: Uninstall VM
  hosts: hypervisor
  vars:
    ansible_user: virtualization-admin

  tasks:
    - name: Destroy VM
      community.libvirt.virt:
        state: destroyed
        name: test_vm

    - name: Undefine VM
      community.libvirt.virt:
        command: undefine
        name: test_vm

    - name: Undefine network
      community.libvirt.virt_net:
        state: absent
        name: test_vm_network

    - name: Undefine pool
      community.libvirt.virt_pool:
        state: absent
        name: test_vm_pool
