- name: 'Install initial configuration'
  hosts: 'hypervisor'
  become: true
  vars:
    ansible_user: 'admin'

  tasks:
    - name: 'Install packages'
      ansible.builtin.apt:
        name:
          - 'curl'
          - 'python3-lxml'
          - 'qemu-system-x86'
          - 'libvirt-daemon-system'
          - 'python3-libvirt'
          - 'libguestfs-tools'
          - 'bridge-utils'
          - 'genisoimage'
        state: 'present'
        update_cache: 'yes'

    - name: 'Copy network interfaces config'
      ansible.builtin.copy:
        src: 'interfaces'
        dest: '/etc/network/interfaces'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Restart networking'
      ansible.builtin.systemd_service:
        name: 'networking.service'
        state: 'restarted'

    - name: 'Copy sshd_config'
      ansible.builtin.copy:
        src: 'sshd_config'
        dest: '/etc/ssh/sshd_config'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Restart sshd'
      ansible.builtin.systemd_service:
        name: 'ssh.service'
        state: 'restarted'

    - name: 'Create user for virtualization management'
      ansible.builtin.user:
        name: 'virtualization-admin'
        comment: 'User for virtualization management'
        groups:
          - 'libvirt'
          - 'kvm'
        shell: '/bin/bash'

    - name: 'Set authorized key for user virtualization-admin'
      ansible.posix.authorized_key:
        user: 'virtualization-admin'
        state: 'present'
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/personal_id_ed25519.pub') }}"

    - name: 'Copy qemu config'
      ansible.builtin.copy:
        src: 'qemu.conf'
        dest: '/etc/libvirt/qemu.conf'
        owner: 'root'
        group: 'root'
        mode: '0600'

    - name: 'Restart libvirtd'
      ansible.builtin.systemd_service:
        name: 'libvirtd.service'
        state: 'restarted'

    - name: 'Ensure that base images path exist'
      file:
        path: '/home/virtualization-admin/libvirt/images'
        state: 'directory'
        mode: 'u=rwx,g=rx,o=rx'
        owner: 'virtualization-admin'
        group: 'virtualization-admin'

    - name: 'Download base Debian cloud image' # https://cloud.debian.org/images/cloud/
      ansible.builtin.get_url:
        url: 'https://cloud.debian.org/images/cloud/bookworm/20240211-1654/debian-12-generic-amd64-20240211-1654.qcow2'
        dest: '/home/virtualization-admin/libvirt/images/debian-12-generic-amd64.qcow2'
        mode: 'u=rwx,g=rx,o=rx'
        owner: 'virtualization-admin'
        group: 'virtualization-admin'

    - name: 'Download base Ubuntu cloud image' # https://cloud.debian.org/images/cloud/
      ansible.builtin.get_url:
        url: 'https://cloud-images.ubuntu.com/daily/server/jammy/20240319/jammy-server-cloudimg-amd64-disk-kvm.img'
        dest: '/home/virtualization-admin/libvirt/images/jammy-server-cloudimg-amd64-disk-kvm.img'
        mode: 'u=rwx,g=rx,o=rx'
        owner: 'virtualization-admin'
        group: 'virtualization-admin'
